---
- hosts: localhost
  connection: local
  vars:
    plugins_path: "{{ ansible_env.HOME }}/.tmux/plugins"

  pre_tasks:

    - name: update cache
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 3600

  tasks:

    - name: Install tmux
      become: true
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: no
      vars:
        packages:
        - tmux
        - gawk

    - name: Create Symlink
      file:
        src: "{{ playbook_dir }}/{{ item }}"
        dest: "{{ ansible_env.HOME }}/{{ item }}"
        state: link
      with_items:
        - .tmux.conf

    - name: Install tmux plugin manager
      git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "{{ plugins_path }}/tpm"
