---
- hosts: localhost
  connection: local
  vars:
    plugins_path: "{{ ansible_env.HOME }}/.tmux/plugins"

  pre_tasks:

  tasks:

    - name: Install tmux
      become: true
      portage: package={{ item }} state=present
      with_items:
        - tmux
        - gawk

    - name: Create Symlink
      file:
        src: "{{ playbook_dir }}/{{ item }}"
        dest: "{{ ansible_env.HOME }}/{{ item }}"
        state: link
      with_items:
        - .tmux.conf
        - .tmux

    - name: Install tmux plugin manager
      git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "{{ plugins_path }}/tpm"
