---
- hosts: localhost
  connection: local

  pre_tasks:
    - name: Update apt cache
      become: true
      apt: update_cache=yes cache_valid_time=3600

  tasks:

    - name: Install languages environment
      become: true
      apt: name={{ item }} state=present
      with_items:
        - racket
