---
- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ common_packages }}"
  tags: [common, install]

- name: Install debian packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - xclip
    - unzip
  tags: [common, install]
