---
- hosts: localhost
  connection: local

  tasks:

#   - name: Install Git and cURL
#     become: true
#     apt: name={{ item }} state=present
#     with_items:
#       - git
#       - curl
#       - vim
#       - xclip

    - name: Install vim plugins
      file:
        src: "{{ playbook_dir}}/{{ item }}"
        dest: "{{ ansible_env.HOME}}/{{ item }}"
        state: link
      with_items:
        - .vimrc
        - .vim
        - .marvim

    - name: Install Plug
      get_url:
        dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
