---
- hosts: localhost
  connection: local

  pre_tasks:
    - name: Update apt cache
      become: true
      apt: update_cache=yes cache_valid_time=3600

  tasks:

    - name: Install Git and cURL
      become: true
      apt: name={{ item }} state=present
      with_items:
        - git
        - curl
        - vim
        - xclip

    - name: Install vim plugins
      file:
        src: "{{ playbook_dir}}/{{ item }}"
        dest: "{{ ansible_env.HOME}}/{{ item }}"
        state: link
      with_items:
        - .vimrc
        - .vim
        - .marvim

    - name: Install Plug
      get_url:
        dest: "{{ ansible_env.HOME }}/.vim/autoload/plugin.vim"
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
