---
- hosts: localhost
  connection: local
  vars:
    pyenv_path:  "{{ ansible_env.HOME }}/.pyenv"
    usr_profile: "{{ ansible_env.HOME }}/.zshrc.user"

  tasks:

    - name: Clone pyenv repo
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: "{{ pyenv_path }}"

    - name: Check whether pyenv is configured
      command: grep "PYENV_ROOT" "{{ usr_profile }}"
      register: checkpyenv
      check_mode: no
      ignore_errors: yes
      changed_when: no

    - name: Configure pyenv environment
      shell: |
        printf '
        # pyenv config
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        if command -v pyenv 1>/dev/null 2>&1; then
        \teval "$(pyenv init -)"
        fi
        ' >> "{{ usr_profile }}"
      when: checkpyenv.rc == 1

    - name: Install poetry
      shell: >
        curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      args:
        creates: "{{ ansible_env.HOME }}/.poetry"

    - name: Clone pyenv virtualenv
      git:
        repo: https://github.com/pyenv/pyenv-virtualenv.git
        dest: "{{ pyenv_path }}/plugins/pyenv-virtualenv"
