---
- import_tasks: debian.yaml
  when: ansible_facts['os_family']|lower == 'debian'
  tags: [zsh, install]

- name: Configure ZSH
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    state: link
  with_items: "{{ zsh_configs }}"
  tags: [zsh, configure]

- name: Install Oh-My-ZSH
  shell: >
      curl -fsSL "{{ zsh_omz_url }}" | sh
  args:
    creates: "{{ zsh_omz_dir }}"
  tags: [zsh, install]
