---

- import_tasks: debian.yaml
  when: ansible_facts['os_family']|lower == 'debian'
  tags: [vim, install]

- name: Install vim extensions
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME}}/.{{ item }}"
    state: link
    force: yes
  with_items: "{{ vim_extensions }}"
  tags: [vim, configure]

- name: Ensure vim autoload path was created
  file:
    path: "{{ vim_plug_dir }}"
    state: directory
  tags: [vim, configure]

- name: Install Plug (Plugin Manager)
  get_url:
    dest: "{{ vim_plug_dir}}/plug.vim"
    url: "{{ vim_plug_url }}"
  tags: [vim, configure]
